/:
  controller: MainController
  action: home

/copyright:
  controller: MainController
  action: copyright

/legal:
  controller: MainController
  action: legal

/privacy:
  controller: MainController
  action: privacy

/refund:
  controller: MainController
  action: refund

/terms:
  controller: MainController
  action: terms

/login:
  controller: SecurityController
  type: GET | POST
  action: login

/logout:
  controller: SecurityController
  action: logout

/register:
  controller: SecurityController
  type: GET | POST
  action: register

/verification:
  controller: SecurityController
  type: GET | POST
  action: verification

/reset-password:
  controller: SecurityController
  type: GET | POST
  action: passwordReset

/verification/sendVerificationCode:
  controller: SecurityController
  type: GET
  action: sendVerificationCode

/home:
  controller: MainController
  action: home

/products:
  controller: ProductController
  action: index
  method: GET

/orders:
  controller: OrderController
  action: index

/orders/payment-info:
  controller: OrderController
  action: paymentInfo

/orders/summary:
  controller: OrderController
  action: summary

/admin/dashboard:
  controller: AdminController
  action: dashboard

/admin/pages:
  controller: AdminController
  action: pages

/admin/products:
  controller: AdminController
  action: products
  role: 10
  method: POST | GET

/admin/product/edit:
  controller: ProductController
  action: edit
  role: 10
  method: GET | POST

/admin/products/delete:
  controller: ProductController
  action: delete
  role: 10
  method: DELETE

/admin/settings:
  controller: AdminController
  action: settings

/admin/frameworksettings:
  controller: AdminController
  type: GET | POST
  action: frameworksettings

/admin/profile:
  controller: AdminController
  action: profile

/admin/notifications:
  controller: AdminController
  action: notifications
