/:
  controller: MainController
  action: home

/login:
  controller: SecurityController
  action: login

/logout:
  controller: SecurityController
  action: logout

/register:
  controller: SecurityController
  action: register

/home:
  controller: MainController
  action: home

/products:
  controller: ProductController
  action: index

/cart:
  controller: CartController
  action: cart

/orders:
  controller: OrderController
  action: index

/admin/dashboard:
  controller: AdminController
  action: dashboard

/admin/pages:
  controller: AdminController
  action: pages

/admin/products:
  controller: AdminController
  action: products

/admin/settings:
  controller: AdminController
  action: settings

/admin/profile:
  controller: AdminController
  action: profile

/admin/notifications:
  controller: AdminController
  action: notifications

/welcome:
  controller: ConfigController
  action: welcome