/:
  controller: MainController
  action: home

/copyright:
  controller: MainController
  action: copyright

/legal:
  controller: MainController
  action: legal

/privacy:
  controller: MainController
  action: privacy

/refund:
  controller: MainController
  action: refund

/terms:
  controller: MainController
  action: terms

/login:
  controller: SecurityController
  type: GET | POST
  action: login

/logout:
  controller: SecurityController
  action: logout

/register:
  controller: SecurityController
  type: GET | POST
  action: register

/verification:
  controller: SecurityController
  type: GET | POST
  action: verification

/reset-password:
  controller: SecurityController
  type: GET | POST
  action: passwordReset

/verification/sendVerificationCode:
  controller: SecurityController
  type: GET
  action: sendVerificationCode

/home:
  controller: MainController
  action: home

/products:
  controller: ProductController
  action: index
  method: GET

/product/comment:
  controller: ReviewController
  action: addComment
  method: POST
  role: 1

/orders:
  controller: OrderController
  action: index

/orders/payment-info:
  controller: OrderController
  action: paymentInfo
  method: GET | POST
  role: 1

/orders/summary:
  controller: OrderController
  action: summary
  method: GET | POST
  role: 1

/orders/completed:
  controller: OrderController
  action: completed
  method: GET
  role: 1

/orders/add_product:
  controller: OrderController
  action: addProduct
  method: POST
  role: 1

/order-slot:
  controller: OrderController
  action: updateOrderSlot
  method: POST | DELETE
  role: 1

/admin/dashboard:
  controller: AdminController
  action: dashboard
  role: 5

/admin/pages:
  controller: AdminController
  action: pages
  role: 5

/admin/products:
  controller: AdminController
  action: products
  role: 5
  method: POST | GET

/admin/product/edit:
  controller: ProductController
  action: edit
  role: 5
  method: GET | POST

/admin/products/delete:
  controller: ProductController
  action: delete
  role: 10
  method: DELETE

/admin/settings:
  controller: AdminController
  action: settings
  role: 10

/admin/frameworksettings:
  controller: AdminController
  type: GET | POST
  action: frameworksettings
  role: 5

/profile:
  controller: AdminController
  action: profile
  role: 1

/user/delete:
  controller: AdminController
  action: deleteUser
  method: GET | DELETE | POST
  role: 1

/admin/comments:
  controller: AdminController
  action: comments
  role: 5

/admin/comments/evaluate:
  controller: ReviewController
  action: evaluate
  method: GET
  role: 5

/admin/users:
  controller: AdminController
  action: users
  role: 10

/admin/changerole:
  controller: AdminController
  type: POST
  action: changeUserRole
  role: 10

/admin/designguide:
  controller: AdminController
  action: designguide
  role: 5
