/:
  controller: MainController
  action: home

/login:
  controller: SecurityController
  type: GET | POST
  action: login

/logout:
  controller: SecurityController
  action: logout

/register:
  controller: SecurityController
  type: GET | POST
  action: register

/verification:
  controller: SecurityController
  type: GET | POST
  action: verification

/verification/sendVerificationCode:
  controller: SecurityController
  type: GET
  action: sendVerificationCode

/home:
  controller: MainController
  action: home

/products:
  controller: ProductController
  action: index

/orders:
  controller: OrderController
  action: index

/orders/payment-info:
  controller: OrderController
  action: paymentInfo

/orders/summary:
  controller: OrderController
  action: summary

/admin/dashboard:
  controller: AdminController
  action: dashboard

/admin/pages:
  controller: AdminController
  action: pages

/admin/products:
  controller: AdminController
  action: products

/admin/settings:
  controller: AdminController
  action: settings

/admin/profile:
  controller: AdminController
  action: profile

/admin/notifications:
  controller: AdminController
  action: notifications

/welcome:
  controller: ConfigController
  action: welcome