/:
  controller: MainController
  action: home

/login:
  controller: SecurityController
  action: login

/logout:
  controller: SecurityController
  action: logout

/register:
  controller: SecurityController
  action: register

/home:
  controller: MainController
  action: home

/products:
  controller: ProductController
  action: index

/orders:
  controller: OrderController
  action: index