-------- INSERTS --------

INSERT INTO rbnm_user (firstName, lastName, email, pwd, status, role) VALUES
    ('John', 'Doe', 'john.doe@example.com', '$2y$10$K.opOJbgF69Ma7PTdS9rReooHAWeXLJ6CdASD0As6jnd7PYNSuS', 1, 1),
    ('Jane', 'Smith', 'jane.smith@example.com', '$2y$10$K.opOJbgF69Ma7PTdS9rReooHAWeXLJ6CdASD0As6jnd7PYNSuS', 1, 1),
    ('Michael', 'Johnson', 'michael.johnson@example.com', '$2y$10$K.opOJbgF69Ma7PTdS9rReooHAWeXLJ6CdASD0As6jnd7PYNSuS', 1, 1),
    ('Emily', 'Brown', 'emily.brown@example.com', '$2y$10$K.opOJbgF69Ma7PTdS9rReooHAWeXLJ6CdASD0As6jnd7PYNSuS', 1, 1),
    ('Daniel', 'Davis', 'daniel.davis@example.com', '$2y$10$K.opOJbgF69Ma7PTdS9rReooHAWeXLJ6CdASD0As6jnd7PYNSuS', 1, 1),
    ('Olivia', 'Miller', 'olivia.miller@example.com', '$2y$10$K.opOJbgF69Ma7PTdS9rReooHAWeXLJ6CdASD0As6jnd7PYNSuS', 1, 1),
    ('William', 'Wilson', 'william.wilson@example.com', '$2y$10$K.opOJbgF69Ma7PTdS9rReooHAWeXLJ6CdASD0As6jnd7PYNSuS', 1, 1),
    ('Sophia', 'Anderson', 'sophia.anderson@example.com', '$2y$10$K.opOJbgF69Ma7PTdS9rReooHAWeXLJ6CdASD0As6jnd7PYNSuS', 1, 1),
    ('James', 'Taylor', 'james.taylor@example.com', '$2y$10$K.opOJbgF69Ma7PTdS9rReooHAWeXLJ6CdASD0As6jnd7PYNSuS', 1, 1),
    ('Emma', 'Thomas', 'emma.thomas@example.com', '$2y$10$K.opOJbgF69Ma7PTdS9rReooHAWeXLJ6CdASD0As6jnd7PYNSuS', 1, 1);

INSERT INTO rbnm_user (firstName, lastName, email, pwd, status, role) VALUES
    ('Alex', 'Clark', 'alex.clark@example.com', '$2y$10$K.opOJbgF69Ma7PTdS9rReooHAWeXLJ6CdASD0As6jnd7PYNSuS', 1, 5),
    ('Grace', 'Walker', 'grace.walker@example.com', '$2y$10$K.opOJbgF69Ma7PTdS9rReooHAWeXLJ6CdASD0As6jnd7PYNSuS', 1, 5),
    ('Benjamin', 'Harris', 'benjamin.harris@example.com', '$2y$10$K.opOJbgF69Ma7PTdS9rReooHAWeXLJ6CdASD0As6jnd7PYNSuS', 1, 5),
    ('Lily', 'Lewis', 'lily.lewis@example.com', '$2y$10$K.opOJbgF69Ma7PTdS9rReooHAWeXLJ6CdASD0As6jnd7PYNSuS', 1, 5),
    ('Henry', 'Martin', 'henry.martin@example.com', '$2y$10$K.opOJbgF69Ma7PTdS9rReooHAWeXLJ6CdASD0As6jnd7PYNSuS', 1, 5);

INSERT INTO rbnm_user (firstName, lastName, email, pwd, status, role) VALUES
    ('Adam', 'White', 'adam.white@example.com', '$2y$10$K.opOJbgF69Ma7PTdS9rReooHAWeXLJ6CdASD0As6jnd7PYNSuS', 1, 10),
    ('Ella', 'Jones', 'ella.jones@example.com', '$2y$10$K.opOJbgF69Ma7PTdS9rReooHAWeXLJ6CdASD0As6jnd7PYNSuS', 1, 10);

INSERT INTO rbnm_category (name, amount, unit) VALUES 
    ('Fruits', 1, 'kg'),
    ('Légumes', 1, 'kg'),
    ('Viandes', 1, 'kg'),
    ('Poissons', 1, 'kg'),
    ('Produits laitiers', 1, 'l'),
    ('Boissons', 1, 'l'),
    ('Epicerie', 1, 'g'),
    ('Boulangerie', 1, 'kg'),
    ('Patisserie', 1, 'kg');

INSERT INTO rbnm_product (name, image, description, price, stock, categoryId) VALUES
    ('Pommes', 'documents/products/pommes.jpg', 'Les pommes sont des fruits délicieux et croquants, parfaits pour une collation saine et rafraîchissante. Elles sont riches en fibres et en vitamines, et sont cultivées avec soin pour garantir une qualité optimale.', 2, 10, 1),
    ('Bananes', 'documents/products/bananes.jpg', 'Les bananes sont des fruits savoureux et énergétiques, idéaux pour un en-cas rapide ou pour ajouter une touche sucrée à vos recettes préférées. Elles sont riches en potassium et en vitamines essentielles.', 3, 15, 1),
    ('Oranges', 'documents/products/oranges.jpg', 'Les oranges sont des agrumes juteux et rafraîchissants, parfaits pour faire le plein de vitamine C. Leur saveur acidulée et sucrée en fait un choix parfait pour les jus frais ou pour ajouter une touche d''agrumes à vos plats.', 2, 8, 1),
    ('Carottes', 'documents/products/carottes.jpg', 'Les carottes sont des légumes croquants et nutritifs, riches en vitamines et en antioxydants. Elles sont polyvalentes et peuvent être utilisées dans une variété de plats, des salades aux soupes en passant par les plats mijotés.', 1, 20, 2),
    ('Tomates', 'documents/products/tomates.jpg', 'Les tomates sont des fruits juteux et savoureux, parfaits pour ajouter de la fraîcheur à vos plats. Elles sont riches en lycopène, un antioxydant puissant, et peuvent être utilisées dans une variété de recettes, des salades aux sauces.', 2, 12, 2),
    ('Salade', 'documents/products/salade.jpg', 'La salade est un légume frais et croquant, idéal pour préparer des salades saines et équilibrées. Elle est polyvalente et peut être associée à une variété d''ingrédients pour créer des combinaisons de saveurs délicieuses.', 2, 10, 2),
    ('Poulet', 'documents/products/poulet.jpg', 'Le poulet est une viande maigre et savoureuse, parfaite pour une alimentation équilibrée. Il peut être préparé de différentes manières, des grillades aux ragoûts, et est une excellente source de protéines.', 5, 6, 3),
    ('Boeuf', 'documents/products/boeuf.jpg', 'Le boeuf est une viande tendre et savoureuse, idéale pour les amateurs de viande. Il peut être cuisiné de différentes façons, des steaks grillés aux rôtis mijotés, et est une excellente source de protéines et de fer.', 8, 4, 3),
    ('Porc', 'documents/products/porc.jpg', 'Le porc est une viande juteuse et savoureuse, parfaite pour une variété de plats. Des côtes de porc grillées aux sautés de porc, il offre une texture et une saveur uniques qui satisferont les papilles gustatives.', 6, 5, 3),
    ('Saumon', 'documents/products/saumon.jpg', 'Le saumon est un poisson délicieux et nutritif, riche en acides gras oméga-3 bénéfiques pour la santé. Il peut être grillé, cuit au four ou utilisé dans des recettes de sushi pour une expérience culinaire exceptionnelle.', 10, 3, 4),
    ('Truite', 'documents/products/truite.jpg', 'La truite est un poisson frais et délicieux, souvent pêché localement pour garantir une qualité optimale. Elle peut être préparée de différentes manières, des grillades aux papillotes, et offre une chair tendre et savoureuse.', 7, 4, 4),
    ('Thon', 'documents/products/thon.jpg', 'Le thon est un poisson à la chair ferme et savoureuse, idéal pour les amateurs de fruits de mer. Il peut être grillé, poêlé ou utilisé dans des recettes de sushi pour ajouter une touche de saveur marine à vos repas.', 9, 6, 4),
    ('Lait', 'documents/products/lait.jpg', 'Le lait est une boisson riche en calcium et en vitamines essentielles, idéale pour renforcer les os et favoriser une croissance saine. Il peut être consommé tel quel, utilisé dans des recettes de desserts ou ajouté à des boissons chaudes.', 2, 10, 5),
    ('Yaourt', 'documents/products/yaourt.jpg', 'Le yaourt est un produit laitier crémeux et délicieux, parfait pour une collation saine ou pour accompagner vos plats préférés. Il est riche en probiotiques bénéfiques pour la digestion et en calcium pour des os solides.', 1, 15, 5),
    ('Fromage', 'documents/products/fromage.jpg', 'Le fromage est un produit laitier savoureux et polyvalent, idéal pour ajouter une touche de richesse et de saveur à vos plats. Des fromages doux aux fromages forts, il existe une variété de choix pour satisfaire tous les palais.', 3, 8, 5),
    ('Eau', 'documents/products/eau.jpg', 'L''eau est une boisson essentielle pour rester hydraté et maintenir un équilibre hydrique optimal. Elle est naturellement sans calories et peut être consommée seule ou utilisée comme base pour des boissons rafraîchissantes.', 1, 20, 6),
    ('Jus d''orange', 'documents/products/jus_de_orange.jpg', 'Le jus d''orange est une boisson rafraîchissante et pleine de vitamine C, parfaite pour commencer la journée avec énergie. Il est pressé à partir d''oranges fraîches pour préserver les nutriments et la saveur naturelle.', 2, 12, 6),
    ('Soda', 'documents/products/soda.jpg', 'Les sodas sont des boissons rafraîchissantes et pétillantes, idéales pour se désaltérer lors de moments de détente. Ils sont disponibles dans une variété de saveurs et peuvent être appréciés seuls ou mélangés à d''autres boissons.', 1, 10, 6),
    ('Riz', 'documents/products/riz.jpg', 'Le riz est un aliment de base polyvalent, idéal pour accompagner une variété de plats. Du riz blanc au riz complet, il existe différentes variétés pour satisfaire tous les goûts et ajouter de la texture à vos repas.', 3, 10, 7),
    ('Pâtes', 'documents/products/pâtes.jpg', 'Les pâtes sont un aliment réconfortant et polyvalent, parfait pour créer des plats savoureux et nourrissants. Des spaghettis aux lasagnes, il existe une variété de formes et de sauces pour satisfaire toutes les envies.', 2, 15, 7),
    ('Huile d''olive', 'documents/products/huile_de_olive.jpg', 'L''huile d''olive est une huile végétale saine et savoureuse, utilisée dans de nombreuses cuisines à travers le monde. Elle peut être utilisée pour assaisonner les salades, cuire les aliments ou ajouter une touche de saveur aux plats.', 5, 8, 7);

INSERT INTO rbnm_review (userId, productId, rating, comment, isApproved) VALUES
    (1, 1, 4, 'Très bonnes pommes fraîches et croquantes. Je recommande.', TRUE),
    (2, 1, 3, 'Les pommes sont vraiment délicieuses. Elles sont croquantes et juteuses, parfaites pour une collation saine. Je les recommande vivement !', TRUE),
    (3, 1, 4, 'J''adore ces pommes ! Elles ont une saveur sucrée et une texture parfaite. Je les achète régulièrement et je ne suis jamais déçu.', TRUE),
    (4, 1, 5, 'Ces pommes sont les meilleures que j''ai jamais goûtées ! Elles sont incroyablement savoureuses et fraîches. Je les recommande à tous les amateurs de pommes.', TRUE),
    (5, 1, 5, 'Malheureusement, j''ai reçu ma commande sans les pommes. J''espère que ce problème sera résolu rapidement.', TRUE),
    (6, 2, 4, 'Les bananes sont délicieuses et bien mûres. Elles sont parfaites pour faire des smoothies ou pour une collation rapide.', TRUE),
    (7, 2, 3, 'J''aime beaucoup ces bananes. Elles sont douces et ont une texture agréable. Je les ajoute souvent à mes céréales du matin.', TRUE),
    (8, 2, 4, 'Ces bananes sont vraiment délicieuses. Elles sont sucrées et ont une saveur intense. Je les recommande vivement !', TRUE),
    (9, 2, 5, 'Les bananes de ce marché sont les meilleures que j''ai jamais goûtées. Elles sont toujours fraîches et savoureuses. Je suis un client fidèle.', TRUE),
    (10, 2, 5, 'Malheureusement, ma commande de bananes était incomplète. J''espère que cela ne se reproduira pas à l''avenir.', TRUE),
    (3, 3, 4, 'Les oranges sont vraiment délicieuses. Elles sont juteuses et ont une saveur sucrée. Je les recommande vivement à tous les amateurs d''agrumes.', TRUE),
    (6, 3, 5, 'J''aime beaucoup ces oranges. Elles sont fraîches et ont une saveur intense. Je les utilise souvent pour faire des jus frais.', TRUE),
    (8, 3, 4, 'Ces oranges sont incroyablement savoureuses. Elles sont juteuses et ont une saveur acidulée délicieuse. Je les achète régulièrement.', TRUE),
    (10, 3, 5, 'Les oranges de ce marché sont les meilleures que j''ai jamais goûtées. Elles sont toujours fraîches et juteuses. Je suis un client fidèle.', TRUE),
    (4, 3, 2, 'Malheureusement, ma commande d''oranges était incomplète. J''espère que cela ne se reproduira pas à l''avenir.', TRUE),
    (4, 4, 5, 'Les carottes de ce marché sont vraiment exceptionnelles. Elles sont fraîches, croquantes et pleines de saveur. Je les recommande vivement !', TRUE),
    (5, 4, 2, 'Malheureusement, ma commande de carottes était incomplète. J''espère que cela ne se reproduira pas à l''avenir.', TRUE),
    (6, 5, 4, 'Les tomates sont vraiment délicieuses. Elles sont juteuses et ont une saveur sucrée. Je les utilise souvent dans mes salades.', TRUE),
    (7, 5, 3, 'J''aime beaucoup ces tomates. Elles sont fraîches et ont une texture agréable. Je les ajoute souvent à mes sandwichs.', TRUE),
    (8, 5, 5, 'Ces tomates sont incroyablement savoureuses. Elles sont juteuses et ont une saveur intense. Je les achète régulièrement.', TRUE),
    (9, 5, 5, 'Les tomates de ce marché sont les meilleures que j''ai jamais goûtées. Elles sont toujours fraîches et savoureuses. Je suis un client fidèle.', TRUE),
    (10, 5, 2, 'Malheureusement, ma commande de tomates était incomplète. J''espère que cela ne se reproduira pas à l''avenir.', TRUE),
    (1, 6, 1, 'La salade est vraiment délicieuse. Elle est fraîche, croquante et pleine de saveur. Je l''utilise souvent comme base pour mes salades.', TRUE),
    (2, 6, 3, 'J''aime beaucoup cette salade. Elle est fraîche et a une texture agréable. Je l''ajoute souvent à mes repas.', TRUE),
    (3, 6, 1, 'Cette salade est incroyablement savoureuse. Elle est fraîche et a une saveur intense. Je l''achète régulièrement.', TRUE),
    (4, 6, 5, 'La salade de ce marché est la meilleure que j''ai jamais goûtée. Elle est toujours fraîche et savoureuse. Je suis un client fidèle.', TRUE),
    (5, 6, 2, 'Malheureusement, ma commande de salade était incomplète. J''espère que cela ne se reproduira pas à l''avenir.', TRUE),
    (6, 7, 4, 'Le poulet est vraiment délicieux. Il est tendre, juteux et plein de saveur. Je l''utilise souvent dans mes recettes.', TRUE),
    (9, 7, 5, 'Le poulet de ce marché est le meilleur que j''ai jamais goûté. Il est toujours frais et savoureux. Je suis un client fidèle.', TRUE),
    (10, 7, 2, 'Malheureusement, ma commande de poulet était incomplète. J''espère que cela ne se reproduira pas à l''avenir.', TRUE),
    (1, 8, 5, 'Le boeuf est vraiment délicieux. Il est tendre, juteux et plein de saveur. Je l''utilise souvent dans mes recettes.', TRUE),
    (2, 8, 5, 'J''aime beaucoup ce boeuf. Il est tendre et a une saveur agréable. Je l''ajoute souvent à mes plats.', TRUE),
    (3, 8, 4, 'Ce boeuf est incroyablement savoureux. Il est tendre et a une saveur intense. Je l''achète régulièrement.', TRUE),
    (4, 8, 5, 'Le boeuf de ce marché est le meilleur que j''ai jamais goûté. Il est toujours frais et savoureux. Je suis un client fidèle.', TRUE),
    (7, 9, 3, 'Le porc est bon. Il est juteux et a une saveur agréable. Je l''utilise souvent dans mes recettes.', TRUE),
    (8, 9, 4, 'Ce porc est délicieux. Il est juteux et a une saveur intense. Je l''achète régulièrement.', TRUE),
    (9, 9, 5, 'Le porc de ce marché est le meilleur que j''ai jamais goûté. Il est toujours frais et savoureux. Je suis un client fidèle.', TRUE),
    (10, 9, 2, 'Malheureusement, ma commande de porc était incomplète. J''espère que cela ne se reproduira pas à l''avenir.', TRUE),
    (1, 10, 2, 'Le saumon est vraiment délicieux. Il est tendre, juteux et plein de saveur. Je l''utilise souvent dans mes recettes.', TRUE),
    (5, 10, 2, 'Malheureusement, ma commande de saumon était incomplète. J''espère que cela ne se reproduira pas à l''avenir.', TRUE),
    (6, 11, 1, 'La truite est vraiment délicieuse. Elle est tendre, juteuse et pleine de saveur. Je l''utilise souvent dans mes recettes.', TRUE),
    (7, 11, 3, 'J''aime beaucoup cette truite. Elle est tendre et a une saveur agréable. Je l''ajoute souvent à mes plats.', TRUE),
    (8, 11, 4, 'Cette truite est incroyablement savoureuse. Elle est tendre et a une saveur intense. Je l''achète régulièrement.', TRUE),
    (2, 12, 3, 'J''aime beaucoup ce thon. Il est tendre et a une saveur agréable. Je l''ajoute souvent à mes recettes.', TRUE),
    (3, 12, 3, 'Ce thon est délicieux. Il est tendre et a une saveur intense. Je l''achète régulièrement.', TRUE),
    (4, 12, 5, 'Le thon de ce marché est le meilleur que j''ai jamais goûté. Il est toujours frais et savoureux. Je suis un client fidèle.', TRUE),
    (5, 12, 4, 'Malheureusement, ma commande de thon était incomplète. J''espère que cela ne se reproduira pas à l''avenir.', TRUE),
    (6, 13, 4, 'Le lait est vraiment délicieux. Il est crémeux et a une saveur agréable. Je l''utilise souvent dans mes recettes.', TRUE),
    (7, 13, 3, 'J''aime beaucoup ce lait. Il est crémeux et a une saveur agréable. Je l''ajoute souvent à mes boissons.', TRUE),
    (8, 13, 1, 'Ce lait est incroyablement savoureux. Il est crémeux et a une saveur intense. Je l''achète régulièrement.', TRUE),
    (9, 13, 1, 'Le lait de ce marché est le meilleur que j''ai jamais goûté. Il est toujours frais et savoureux. Je suis un client fidèle.', TRUE),
    (10, 13, 1, 'Malheureusement, ma commande de lait était incomplète. J''espère que cela ne se reproduira pas à l''avenir.', TRUE),
    (1, 14, 4, 'Le yaourt est vraiment délicieux. Il est crémeux et a une saveur agréable. Je l''utilise souvent comme collation.', TRUE),
    (2, 14, 4, 'J''aime beaucoup ce yaourt. Il est crémeux et a une saveur agréable. Je l''ajoute souvent à mes desserts.', TRUE),
    (5, 14, 2, 'Malheureusement, ma commande de yaourt était incomplète. J''espère que cela ne se reproduira pas à l''avenir.', TRUE),
    (6, 15, 4, 'Le fromage est vraiment délicieux. Il est crémeux et a une saveur agréable. Je l''utilise souvent dans mes recettes.', TRUE),
    (7, 15, 3, 'J''aime beaucoup ce fromage. Il est crémeux et a une saveur agréable. Je l''ajoute souvent à mes plats.', TRUE),
    (8, 15, 4, 'Ce fromage est incroyablement savoureux. Il est crémeux et a une saveur intense. Je l''achète régulièrement.', TRUE),
    (9, 15, 3, 'Le fromage de ce marché est le meilleur que j''ai jamais goûté. Il est toujours frais et savoureux. Je suis un client fidèle.', TRUE),
    (10, 15, 2, 'Malheureusement, ma commande de fromage était incomplète. J''espère que cela ne se reproduira pas à l''avenir.', TRUE),
    (4, 16, 2, 'L''eau de ce marché est la meilleure que j''ai jamais goûtée. Elle est toujours fraîche et savoureuse. Je suis un client fidèle.', TRUE),
    (6, 17, 2, 'Le jus d''orange est vraiment délicieux. Il est frais et a une saveur agréable. Je l''utilise souvent pour commencer ma journée.', TRUE),
    (7, 17, 3, 'J''aime beaucoup ce jus d''orange. Il est frais et a une saveur agréable. Je l''ajoute souvent à mes boissons.', TRUE),
    (8, 17, 4, 'Ce jus d''orange est incroyablement savoureux. Il est frais et a une saveur intense. Je l''achète régulièrement.', TRUE),
    (9, 17, 5, 'Le jus d''orange de ce marché est le meilleur que j''ai jamais goûté. Il est toujours frais et savoureux. Je suis un client fidèle.', TRUE),
    (10, 17, 5, 'Malheureusement, ma commande de jus d''orange était incomplète. J''espère que cela ne se reproduira pas à l''avenir.', TRUE),
    (1, 18, 1, 'Le soda est vraiment délicieux. Il est rafraîchissant et a une saveur agréable. Je l''utilise souvent comme boisson désaltérante.', TRUE),
    (2, 18, 2, 'J''aime beaucoup ce soda. Il est rafraîchissant et a une saveur agréable. Je l''ajoute souvent à mes boissons.', TRUE),
    (5, 18, 2, 'Malheureusement, ma commande de soda était incomplète. J''espère que cela ne se reproduira pas à l''avenir.', TRUE),
    (4, 20, 1, 'Les pâtes de ce marché sont vraiment délicieuses. Elles ont une texture parfaite et une saveur agréable. Je les recommande vivement !', TRUE),
    (5, 20, 1, 'Malheureusement, ma commande de pâtes était incomplète. J''espère que cela ne se reproduira pas à l''avenir.', TRUE),
    (7, 21, 3, 'Cette huile d''olive est vraiment délicieuse. Elle a une saveur intense et ajoute une touche de richesse à mes plats. Je l''achète régulièrement.', TRUE),
    (8, 21, 4, 'Cette huile d''olive est incroyablement savoureuse. Elle a une saveur intense et ajoute une touche de richesse à mes plats. Je la recommande vivement !', TRUE);

INSERT INTO rbnm_order (userId, status) VALUES
    (1, 0),
    (2, 0),
    (6, 0),
    (7, 0),
    (10, 0),
    (10, 1),
    (1, 2),
    (2, 2),
    (10, 2),
    (1, 3),
    (6, 3),
    (7, 3),
    (1, 0),
    (2, 0),
    (10, 0);

INSERT INTO rbnm_order_slot (orderId, productId, quantity) VALUES
    (1, 1, 2),
    (1, 18, 3),
    (1, 2, 1),
    (2, 6, 2),
    (2, 20, 1),
    (3, 7, 2),
    (3, 8, 1),
    (3, 9, 3),
    (4, 16, 2),
    (4, 11, 1),
    (4, 15, 4),
    (4, 3, 1),
    (5, 4, 2),
    (5, 9, 1),
    (5, 10, 3),
    (6, 13, 3),
    (6, 2, 2),
    (6, 5, 3),
    (7, 8, 2),
    (7, 10, 1),
    (8, 16, 2),
    (8, 13, 3),
    (9, 8, 1),
    (9, 9, 3),
    (9, 13, 3),
    (11, 9, 1),
    (11, 10, 3),
    (12, 10, 3),
    (13, 8, 2),
    (13, 9, 1),
    (13, 10, 3),
    (14, 9, 1),
    (14, 10, 3),
    (15, 10, 3),
    (15, 13, 3);

INSERT INTO rbnm_payement_method_type (name, description) VALUES
    ('Carte bancaire', 'Paiement par carte bancaire'),
    ('PayPal', 'Paiement par PayPal'),
    ('Chèque', 'Paiement par chèque');

INSERT INTO rbnm_payment_method (userId, paymentMethodTypeId, cardNumber, expirationDate, securityCode, cardHolderName, cardHolderAddress, cardHolderZipCode, cardHolderCity, cardHolderCountry, cardHolderPhone) VALUES
    (1, 1, '1234567890123456', '12/23', '123', 'John Doe', '1 rue de la Paix', '75000', 'Paris', 'France', '0123456789'),
    (2, 2, '1234567890123456', '12/23', '123', 'Jane Smith', '1 rue de la Paix', '75000', 'Paris', 'France', '0123456789'),
    (3, 3, '1234567890123456', '12/23', '123', 'Michael Johnson', '1 rue de la Paix', '75000', 'Paris', 'France', '0123456789'),
    (4, 1, '1234567890123456', '12/23', '123', 'Emily Brown', '1 rue de la Paix', '75000', 'Paris', 'France', '0123456789'),
    (5, 2, '1234567890123456', '12/23', '123', 'Daniel Davis', '1 rue de la Paix', '75000', 'Paris', 'France', '0123456789'),
    (6, 3, '1234567890123456', '12/23', '123', 'Olivia Miller', '1 rue de la Paix', '75000', 'Paris', 'France', '0123456789'),
    (7, 1, '1234567890123456', '12/23', '123', 'William Wilson', '1 rue de la Paix', '75000', 'Paris', 'France', '0123456789'),
    (8, 2, '1234567890123456', '12/23', '123', 'Sophia Anderson', '1 rue de la Paix', '75000', 'Paris', 'France', '0123456789'),
    (9, 3, '1234567890123456', '12/23', '123', 'James Taylor', '1 rue de la Paix', '75000', 'Paris', 'France', '0123456789'),
    (10, 1, '1234567890123456', '12/23', '123', 'Emma Thomas', '1 rue de la Paix', '75000', 'Paris', 'France', '0123456789');

INSERT INTO rbnm_payment (paymentMethodId, orderId, status) VALUES
    (1, 1, 0),
    (2, 2, 0),
    (3, 3, 0),
    (3, 3, 1),
    (4, 4, 0),
    (5, 5, 0),
    (5, 5, 1),
    (6, 6, 0),
    (7, 7, 0),
    (8, 8, 0),
    (9, 9, 0),
    (10, 10, 0),
    (1, 11, 0),
    (1, 11, 1),
    (2, 12, 0),
    (3, 13, 0),
    (3, 13, 1),
    (4, 14, 0),
    (5, 15, 0);
