-------- INSERTS --------

INSERT INTO rbnm_user (firstName, lastName, email, pwd, status, role) VALUES
    ('John', 'Doe', 'john.doe@example.com', 'password1', 1, 1),
    ('Jane', 'Smith', 'jane.smith@example.com', 'password2', 1, 1),
    ('Michael', 'Johnson', 'michael.johnson@example.com', 'password3', 1, 1),
    ('Emily', 'Brown', 'emily.brown@example.com', 'password4', 1, 1),
    ('Daniel', 'Davis', 'daniel.davis@example.com', 'password5', 1, 1),
    ('Olivia', 'Miller', 'olivia.miller@example.com', 'password6', 1, 1),
    ('William', 'Wilson', 'william.wilson@example.com', 'password7', 1, 1),
    ('Sophia', 'Anderson', 'sophia.anderson@example.com', 'password8', 1, 1),
    ('James', 'Taylor', 'james.taylor@example.com', 'password9', 1, 1),
    ('Emma', 'Thomas', 'emma.thomas@example.com', 'password10', 1, 1);

INSERT INTO rbnm_user (firstName, lastName, email, pwd, status, role) VALUES
    ('Alex', 'Clark', 'alex.clark@example.com', 'password1', 1, 5),
    ('Grace', 'Walker', 'grace.walker@example.com', 'password2', 1, 5),
    ('Benjamin', 'Harris', 'benjamin.harris@example.com', 'password3', 1, 5),
    ('Lily', 'Lewis', 'lily.lewis@example.com', 'password4', 1, 5),
    ('Henry', 'Martin', 'henry.martin@example.com', 'password5', 1, 5);

INSERT INTO rbnm_user (firstName, lastName, email, pwd, status, role) VALUES
    ('Adam', 'White', 'adam.white@example.com', 'password1', 1, 10),
    ('Ella', 'Jones', 'ella.jones@example.com', 'password2', 1, 10);

INSERT INTO rbnm_categorie (name, amount, unit) VALUES 
    ('Fruits', 1, 'kg'),
    ('Légumes', 1, 'kg'),
    ('Viandes', 1, 'kg'),
    ('Poissons', 1, 'kg'),
    ('Produits laitiers', 1, 'kg'),
    ('Boissons', 1, 'l'),
    ('Epicerie', 1, 'kg'),
    ('Boulangerie', 1, 'kg'),
    ('Patisserie', 1, 'kg'),
    ('Surgelés', 1, 'kg'),
    ('Hygiène', 1, 'kg'),
    ('Entretien', 1, 'kg');

INSERT INTO rbnm_product (name, image, description, price, stock, categoryId) VALUES
    ('Pommes', '', 'Délicieuses pommes fraîches', 2, 10, 1),
    ('Bananes', '', 'Bananes mûres et savoureuses', 3, 15, 1),
    ('Oranges', '', 'Juteuses oranges de qualité', 2, 8, 1),
    ('Carottes', '', 'Carottes croquantes et nutritives', 1, 20, 2),
    ('Tomates', '', 'Tomates juteuses et savoureuses', 2, 12, 2),
    ('Salade', '', 'Salade fraîche et croquante', 2, 10, 2),
    ('Poulet', '', 'Filets de poulet tendres et savoureux', 5, 6, 3),
    ('Boeuf', '', 'Steaks de boeuf de qualité supérieure', 8, 4, 3),
    ('Porc', '', 'Côtes de porc juteuses et tendres', 6, 5, 3),
    ('Saumon', '', 'Filets de saumon frais et délicieux', 10, 3, 4),
    ('Truite', '', 'Truites fraîches pêchées localement', 7, 4, 4),
    ('Thon', '', 'Steaks de thon de qualité supérieure', 9, 6, 4),
    ('Lait', '', 'Lait frais de la ferme', 2, 10, 5),
    ('Yaourt', '', 'Yaourts crémeux et délicieux', 1, 15, 5),
    ('Fromage', '', 'Fromages variés et savoureux', 3, 8, 5),
    ('Eau', '', 'Eau minérale naturelle', 1, 20, 6),
    ('Jus d''orange', '', 'Jus d''orange frais pressé', 2, 12, 6),
    ('Soda', '', 'Sodas rafraîchissants', 1, 10, 6),
    ('Riz', '', 'Riz blanc de qualité supérieure', 3, 10, 7),
    ('Pâtes', '', 'Pâtes italiennes traditionnelles', 2, 15, 7),
    ('Huile d''olive', '', 'Huile d''olive extra vierge', 5, 8, 7),
    ('Baguette', '', 'Délicieuses baguettes croustillantes', 1, 20, 8),
    ('Croissant', '', 'Croissants frais et beurrés', 1, 15, 8),
    ('Pain au chocolat', '', 'Pains au chocolat moelleux', 1, 15, 8),
    ('Tarte aux pommes', '', 'Délicieuse tarte aux pommes maison', 5, 6, 9),
    ('Éclair au chocolat', '', 'Éclairs au chocolat fondants', 2, 10, 9),
    ('Mille-feuille', '', 'Mille-feuilles croustillants et crémeux', 4, 8, 9),
    ('Frites', '', 'Frites croustillantes et dorées', 3, 10, 10),
    ('Pizza surgelée', '', 'Pizza surgelée au choix', 5, 6, 10),
    ('Glace', '', 'Délicieuses glaces artisanales', 4, 8, 10),
    ('Savon', '', 'Savon doux pour la peau', 2, 10, 11),
    ('Shampooing', '', 'Shampooing nourrissant pour les cheveux', 3, 8, 11),
    ('Dentifrice', '', 'Dentifrice frais pour une bonne hygiène bucco-dentaire', 2, 10, 11),
    ('Lessive', '', 'Lessive efficace pour un linge propre', 4, 6, 12),
    ('Nettoyant multi-surfaces', '', 'Nettoyant polyvalent pour toutes les surfaces', 3, 8, 12),
    ('Désinfectant', '', 'Désinfectant puissant pour une propreté optimale', 2, 10, 12);

INSERT INTO rbnm_review (userId, productId, rating, comment, isApproved) VALUES
    (1, 1, 4, 'Très bonnes pommes', TRUE),
    (2, 1, 3, 'Bonnes pommes', TRUE),
    (3, 1, 4, 'Délicieuses pommes', TRUE),
    (4, 1, 5, 'Les meilleures pommes du marché', TRUE),
    (5, 1, 2, 'Ils ont oublié de me livrer les pommes', TRUE),
    (6, 2, 4, 'Très bonnes bananes', TRUE),
    (7, 2, 3, 'Bonnes bananes', TRUE),
    (8, 2, 4, 'Délicieuses bananes', TRUE),
    (9, 2, 5, 'Les meilleures bananes du marché', TRUE),
    (10, 2, 2, 'Ils ont oublié de me livrer les bananes', TRUE),
    (3, 3, 4, 'Très bonnes oranges', TRUE),
    (6, 3, 3, 'Bonnes oranges', TRUE),
    (8, 3, 4, 'Délicieuses oranges', TRUE),
    (10, 3, 5, 'Les meilleures oranges du marché', TRUE),
    (4, 3, 2, 'Ils ont oublié de me livrer les oranges', TRUE),
    (4, 4, 5, 'Les meilleures carottes du marché', TRUE),
    (5, 4, 2, 'Ils ont oublié de me livrer les carottes', TRUE),
    (6, 5, 4, 'Très bonnes tomates', TRUE),
    (7, 5, 3, 'Bonnes tomates', TRUE),
    (8, 5, 4, 'Délicieuses tomates', TRUE),
    (9, 5, 5, 'Les meilleures tomates du marché', TRUE),
    (10, 5, 2, 'Ils ont oublié de me livrer les tomates', TRUE),
    (1, 6, 4, 'Très bonne salade', TRUE),
    (2, 6, 3, 'Bonne salade', TRUE),
    (3, 6, 4, 'Délicieuse salade', TRUE),
    (4, 6, 5, 'La meilleure salade du marché', TRUE),
    (5, 6, 2, 'Ils ont oublié de me livrer la salade', TRUE),
    (6, 7, 4, 'Très bon poulet', TRUE),
    (9, 7, 5, 'Le meilleur poulet du marché', TRUE),
    (10, 7, 2, 'Ils ont oublié de me livrer le poulet', TRUE),
    (1, 8, 4, 'Très bon boeuf', TRUE),
    (2, 8, 3, 'Bon boeuf', TRUE),
    (3, 8, 4, 'Délicieux boeuf', TRUE),
    (4, 8, 5, 'Le meilleur boeuf du marché', TRUE),
    (7, 9, 3, 'Bon porc', TRUE),
    (8, 9, 4, 'Délicieux porc', TRUE),
    (9, 9, 5, 'Le meilleur porc du marché', TRUE),
    (10, 9, 2, 'Ils ont oublié de me livrer le porc', TRUE),
    (1, 10, 4, 'Très bon saumon', TRUE),
    (4, 10, 5, 'Le meilleur saumon du marché', TRUE),
    (5, 10, 2, 'Ils ont oublié de me livrer le saumon', TRUE),
    (6, 11, 4, 'Très bonne truite', TRUE),
    (7, 11, 3, 'Bonne truite', TRUE),
    (8, 11, 4, 'Délicieuse truite', TRUE),
    (2, 12, 3, 'Bon thon', TRUE),
    (3, 12, 4, 'Délicieux thon', TRUE),
    (4, 12, 5, 'Le meilleur thon du marché', TRUE),
    (5, 12, 2, 'Ils ont oublié de me livrer le thon', TRUE),
    (6, 13, 4, 'Très bon lait', TRUE),
    (7, 13, 3, 'Bon lait', TRUE),
    (8, 13, 4, 'Délicieux lait', TRUE),
    (9, 13, 5, 'Le meilleur lait du marché', TRUE),
    (10, 13, 2, 'Ils ont oublié de me livrer le lait', TRUE),
    (1, 14, 4, 'Très bon yaourt', TRUE),
    (2, 14, 3, 'Bon yaourt', TRUE),
    (4, 14, 5, 'Le meilleur yaourt du marché', TRUE),
    (5, 14, 2, 'Ils ont oublié de me livrer le yaourt', TRUE),
    (6, 15, 4, 'Très bon fromage', TRUE),
    (7, 15, 3, 'Bon fromage', TRUE),
    (8, 15, 4, 'Délicieux fromage', TRUE),
    (9, 15, 5, 'Le meilleur fromage du marché', TRUE),
    (10, 15, 2, 'Ils ont oublié de me livrer le fromage', TRUE),
    (1, 16, 4, 'Très bonne eau', TRUE),
    (2, 16, 3, 'Bonne eau', TRUE),
    (4, 16, 5, 'La meilleure eau du marché', TRUE),
    (5, 16, 2, 'Ils ont oublié de me livrer l''eau', TRUE),
    (6, 17, 4, 'Très bon jus d''orange', TRUE),
    (7, 17, 3, 'Bon jus d''orange', TRUE),
    (8, 17, 4, 'Délicieux jus d''orange', TRUE),
    (9, 17, 5, 'Le meilleur jus d''orange du marché', TRUE),
    (10, 17, 2, 'Ils ont oublié de me livrer le jus d''orange', TRUE),
    (1, 18, 4, 'Très bon soda', TRUE),
    (2, 18, 3, 'Bon soda', TRUE),
    (5, 18, 2, 'Ils ont oublié de me livrer le soda', TRUE),
    (6, 19, 4, 'Très bon riz', TRUE),
    (7, 19, 3, 'Bon riz', TRUE),
    (8, 19, 4, 'Délicieux riz', TRUE),
    (4, 20, 5, 'Les meilleures pâtes du marché', TRUE),
    (5, 20, 2, 'Ils ont oublié de me livrer les pâtes', TRUE),
    (7, 21, 3, 'Bonne huile d''olive', TRUE),
    (8, 21, 4, 'Délicieuse huile d''olive', TRUE),
    (1, 22, 4, 'Très bonne baguette', TRUE),
    (2, 22, 3, 'Bonne baguette', TRUE),
    (3, 22, 4, 'Délicieuse baguette', TRUE),
    (4, 22, 5, 'La meilleure baguette du marché', TRUE),
    (5, 22, 2, 'Ils ont oublié de me livrer la baguette', TRUE),
    (1, 24, 4, 'Très bon pain au chocolat', TRUE),
    (2, 24, 3, 'Bon pain au chocolat', TRUE),
    (3, 24, 4, 'Délicieux pain au chocolat', TRUE),
    (6, 25, 4, 'Très bonne tarte aux pommes', TRUE),
    (1, 26, 4, 'Très bon éclair au chocolat', TRUE),
    (2, 26, 3, 'Bon éclair au chocolat', TRUE),
    (3, 26, 4, 'Délicieux éclair au chocolat', TRUE),
    (5, 26, 2, 'Ils ont oublié de me livrer l''éclair au chocolat', TRUE),
    (6, 27, 4, 'Très bon mille-feuille', TRUE),
    (7, 27, 3, 'Bon mille-feuille', TRUE),
    (8, 27, 4, 'Délicieux mille-feuille', TRUE),
    (9, 27, 5, 'Le meilleur mille-feuille du marché', TRUE),
    (10, 27, 2, 'Ils ont oublié de me livrer le mille-feuille', TRUE),
    (5, 28, 2, 'Ils ont oublié de me livrer les frites', TRUE),
    (6, 29, 4, 'Très bonne pizza surgelée', TRUE),
    (7, 29, 3, 'Bonne pizza surgelée', TRUE),
    (8, 29, 4, 'Délicieuse pizza surgelée', TRUE),
    (9, 29, 5, 'La meilleure pizza surgelée du marché', TRUE),
    (10, 29, 2, 'Ils ont oublié de me livrer la pizza surgelée', TRUE),
    (1, 30, 4, 'Très bonne glace', TRUE),
    (4, 30, 5, 'La meilleure glace du marché', TRUE),
    (5, 30, 2, 'Ils ont oublié de me livrer la glace', TRUE),
    (6, 31, 4, 'Très bon savon', TRUE),
    (1, 32, 4, 'Très bon shampooing', TRUE),
    (2, 32, 3, 'Bon shampooing', TRUE),
    (4, 32, 5, 'Le meilleur shampooing du marché', TRUE),
    (5, 32, 2, 'Ils ont oublié de me livrer le shampooing', TRUE),
    (6, 33, 4, 'Très bon dentifrice', TRUE),
    (7, 33, 3, 'Bon dentifrice', TRUE),
    (9, 33, 5, 'Le meilleur dentifrice du marché', TRUE),
    (1, 34, 4, 'Très bonne lessive', TRUE),
    (2, 34, 3, 'Bonne lessive', TRUE),
    (4, 34, 5, 'La meilleure lessive du marché', TRUE),
    (7, 35, 3, 'Bon nettoyant multi-surfaces', TRUE),
    (9, 35, 5, 'Le meilleur nettoyant multi-surfaces du marché', TRUE),
    (10, 35, 2, 'Ils ont oublié de me livrer le nettoyant multi-surfaces', TRUE),
    (4, 36, 5, 'Le meilleur désinfectant du marché', TRUE),
    (5, 36, 2, 'Ils ont oublié de me livrer le désinfectant', TRUE);

INSERT INTO rbnm_order (userId, status) VALUES
    (1, 0),
    (2, 0),
    (6, 0),
    (7, 0),
    (10, 0),
    (10, 1),
    (1, 2),
    (2, 2),
    (10, 2),
    (1, 3),
    (6, 3),
    (7, 3),
    (1, 0),
    (2, 0),
    (10, 0);

INSERT INTO rbnm_order_slot (orderId, productId, quantity) VALUES
    (1, 1, 2),
    (1, 18, 3),
    (1, 2, 1),
    (2, 6, 2),
    (2, 20, 1),
    (3, 7, 2),
    (3, 8, 1),
    (3, 9, 3),
    (4, 16, 2),
    (4, 11, 1),
    (4, 15, 4),
    (4, 3, 1),
    (5, 4, 2),
    (5, 9, 1),
    (5, 10, 3),
    (6, 25, 2),
    (6, 24, 1),
    (6, 13, 3),
    (6, 2, 2),
    (6, 24, 1),
    (6, 5, 3),
    (7, 8, 2),
    (7, 10, 1),
    (8, 16, 2),
    (8, 24, 1),
    (8, 13, 3),
    (9, 8, 1),
    (9, 9, 3),
    (9, 25, 2),
    (9, 13, 3),
    (10, 25, 2),
    (10, 24, 1),
    (11, 9, 1),
    (11, 10, 3),
    (11, 25, 2),
    (11, 24, 1),
    (12, 10, 3),
    (12, 25, 2),
    (13, 8, 2),
    (13, 9, 1),
    (13, 10, 3),
    (13, 25, 2),
    (14, 9, 1),
    (14, 10, 3),
    (15, 10, 3),
    (15, 24, 1),
    (15, 13, 3);

INSERT INTO rbnm_payement_method_type (name, description) VALUES
    ('Carte bancaire', 'Paiement par carte bancaire'),
    ('PayPal', 'Paiement par PayPal'),
    ('Chèque', 'Paiement par chèque');

INSERT INTO rbnm_payment_method (userId, paymentMethodTypeId, cardNumber, expirationDate, securityCode, cardHolderName, cardHolderAddress, cardHolderZipCode, cardHolderCity, cardHolderCountry, cardHolderPhone) VALUES
    (1, 1, '1234567890123456', '12/23', '123', 'John Doe', '1 rue de la Paix', '75000', 'Paris', 'France', '0123456789'),
    (2, 2, '1234567890123456', '12/23', '123', 'Jane Smith', '1 rue de la Paix', '75000', 'Paris', 'France', '0123456789'),
    (3, 3, '1234567890123456', '12/23', '123', 'Michael Johnson', '1 rue de la Paix', '75000', 'Paris', 'France', '0123456789'),
    (4, 1, '1234567890123456', '12/23', '123', 'Emily Brown', '1 rue de la Paix', '75000', 'Paris', 'France', '0123456789'),
    (5, 2, '1234567890123456', '12/23', '123', 'Daniel Davis', '1 rue de la Paix', '75000', 'Paris', 'France', '0123456789'),
    (6, 3, '1234567890123456', '12/23', '123', 'Olivia Miller', '1 rue de la Paix', '75000', 'Paris', 'France', '0123456789'),
    (7, 1, '1234567890123456', '12/23', '123', 'William Wilson', '1 rue de la Paix', '75000', 'Paris', 'France', '0123456789'),
    (8, 2, '1234567890123456', '12/23', '123', 'Sophia Anderson', '1 rue de la Paix', '75000', 'Paris', 'France', '0123456789'),
    (9, 3, '1234567890123456', '12/23', '123', 'James Taylor', '1 rue de la Paix', '75000', 'Paris', 'France', '0123456789'),
    (10, 1, '1234567890123456', '12/23', '123', 'Emma Thomas', '1 rue de la Paix', '75000', 'Paris', 'France', '0123456789');

INSERT INTO rbnm_payment (paymentMethodId, orderId, status) VALUES
    (1, 1, 0),
    (2, 2, 0),
    (3, 3, 0),
    (3, 3, 1),
    (4, 4, 0),
    (5, 5, 0),
    (5, 5, 1),
    (6, 6, 0),
    (7, 7, 0),
    (8, 8, 0),
    (9, 9, 0),
    (10, 10, 0),
    (1, 11, 0),
    (1, 11, 1),
    (2, 12, 0),
    (3, 13, 0),
    (3, 13, 1),
    (4, 14, 0),
    (5, 15, 0);
